### ISSUE TITLE
 error TS2339: Property 'safeDump' does not exist on type 'typeof import("C:/dev/spot/node_modules/@types/js-yaml/index")'

### ISSUE THREAD

**Issue by oben01** [airtasker/spot#1317]
**Describe the bug**
Cannot build the project.
The build script failed with this error : 
```
 error TS2339: Property 'safeDump' does not exist on type 'typeof import("C:/dev/spot/node_modules/@types/js-yaml/index")'
```

This error appears after the upgrade of js-yaml to V4.
According to js-yaml [changelog](https://github.com/nodeca/js-yaml/blob/master/migrate_v3_to_v4.md#migration-guide-from-js-yaml3-to-js-yaml4), this error could be fix by changing the safeDump function to dump.

**To Reproduce**
Launch build script from the latest master commit 

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Yarn version v1.22.10
 - Node version v15.11.0
 - Spot version 1.4.0
